# Generated by Django 4.2.1 on 2023-06-03 13:22

import F1.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circuito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('paese', models.CharField(max_length=50)),
                ('capienza_persone', models.PositiveIntegerField()),
                ('lunghezza', models.FloatField(validators=[F1.validators.valida_non_negativi])),
                ('preview', models.CharField(max_length=100)),
                ('immagine_circuito', models.CharField(max_length=100)),
                ('immagine_mappa', models.CharField(max_length=100)),
                ('giro_veloce', models.CharField(max_length=100)),
                ('numero_giri', models.PositiveIntegerField()),
                ('inaugurazione', models.DateField()),
                ('storia', models.CharField(default='', max_length=10000)),
            ],
            options={
                'verbose_name_plural': 'Circuiti',
            },
        ),
        migrations.CreateModel(
            name='Scuderia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descrizione', models.CharField(max_length=50)),
                ('modello_vettura', models.CharField(max_length=50)),
                ('immagine_vettura', models.CharField(max_length=100)),
                ('logo', models.CharField(max_length=100)),
                ('punti', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Scuderie',
            },
        ),
        migrations.CreateModel(
            name='Sessione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Sessioni',
            },
        ),
        migrations.CreateModel(
            name='Pilota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('eta', models.PositiveSmallIntegerField()),
                ('data', models.DateField()),
                ('foto', models.CharField(max_length=100)),
                ('scuderia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='info.scuderia')),
            ],
            options={
                'verbose_name_plural': 'Piloti',
            },
        ),
        migrations.CreateModel(
            name='Partecipazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miglior_tempo', models.CharField(max_length=100, null=True)),
                ('data', models.DateField(null=True)),
                ('circuito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='info.circuito')),
                ('pilota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='info.pilota')),
                ('sessione', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='info.sessione')),
            ],
            options={
                'verbose_name_plural': 'Partecipazioni',
            },
        ),
    ]
