# Generated by Django 4.2.1 on 2023-06-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_partecipazione_posizione'),
    ]

    operations = [
        migrations.AddField(
            model_name='scuderia',
            name='immagine1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='scuderia',
            name='immagine2',
            field=models.CharField(default='', max_length=100),
        ),
    ]
