# Generated by Django 4.2.1 on 2023-06-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_scuderia_immagine1_scuderia_immagine2'),
    ]

    operations = [
        migrations.AddField(
            model_name='partecipazione',
            name='punti',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
