# Generated by Django 4.2.1 on 2023-06-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_partecipazione_punti'),
    ]

    operations = [
        migrations.AddField(
            model_name='scuderia',
            name='campionati_vinti',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scuderia',
            name='modello_power_unit',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='scuderia',
            name='sede',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='scuderia',
            name='team_principal',
            field=models.CharField(default='', max_length=100),
        ),
    ]
