# Generated by Django 4.2.2 on 2023-07-10 12:09

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_remove_pilota_eta_remove_pilota_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuito',
            name='paese',
            field=django_countries.fields.CountryField(blank=True, default=None, max_length=2, null=True),
        ),
    ]
