# Generated by Django 4.2.2 on 2023-07-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_alter_circuito_paese'),
    ]

    operations = [
        migrations.AddField(
            model_name='scuderia',
            name='nome_completo',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='scuderia',
            name='descrizione',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='scuderia',
            name='logo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='scuderia',
            name='modello_vettura',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='scuderia',
            name='nome',
            field=models.CharField(default='', max_length=50),
        ),
    ]
