# Generated by Django 4.2.2 on 2023-07-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_scuderia_nome_completo_alter_scuderia_descrizione_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilota',
            name='numero_pilota',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
