# Generated by Django 4.2.2 on 2023-07-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_pilota_numero_pilota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuito',
            name='giro_veloce',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='circuito',
            name='immagine_circuito',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='circuito',
            name='immagine_mappa',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='circuito',
            name='nome',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='circuito',
            name='preview',
            field=models.CharField(default='', max_length=100),
        ),
    ]
