# Generated by Django 4.2.2 on 2023-07-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0010_alter_circuito_giro_veloce_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuito',
            name='data_evento',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
