# Generated by Django 4.2.4 on 2023-08-19 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0012_rename_immagine1_pilota_immagine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pilota',
            name='immagine2',
        ),
    ]
