# Generated by Django 4.2.1 on 2023-05-21 09:17

import F1.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biglietto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=50)),
                ('prezzo', models.FloatField(validators=[F1.validators.valida_non_negativi])),
                ('numero_posto', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Bliglietti',
            },
        ),
        migrations.CreateModel(
            name='Carrello',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Carrelli',
            },
        ),
        migrations.CreateModel(
            name='Gestore_Circuito',
            fields=[
                ('sito_web', models.CharField(max_length=100)),
                ('indirizzo', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=25)),
                ('iban', models.CharField(max_length=34, validators=[F1.validators.valida_iban])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Gestori circuiti',
            },
        ),
        migrations.CreateModel(
            name='Notifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=100)),
                ('data', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Notifiche',
            },
        ),
        migrations.CreateModel(
            name='Ordine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Ordini',
            },
        ),
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indirizzo', models.CharField(max_length=50)),
                ('paese', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=25)),
                ('immagine_profilo', models.CharField(max_length=100)),
                ('premium', models.DateField(blank=True, null=True)),
                ('carta_credito', models.CharField(max_length=19, null=True, validators=[F1.validators.valida_carta_credito])),
                ('cvv', models.CharField(max_length=3, null=True, validators=[F1.validators.valida_cvv])),
                ('scadenza_carta', models.DateField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Utenti',
            },
        ),
    ]
