# Generated by Django 4.2.1 on 2023-05-31 15:51

import F1.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('info', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gestore_Circuito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sito_web', models.CharField(max_length=100)),
                ('indirizzo', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=25)),
                ('iban', models.CharField(max_length=34, validators=[F1.validators.valida_iban])),
                ('gestione_circuito', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='info.circuito')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Gestori circuiti',
            },
        ),
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indirizzo', models.CharField(max_length=50)),
                ('paese', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=25)),
                ('immagine_profilo', models.CharField(max_length=100)),
                ('premium', models.DateField(blank=True, null=True)),
                ('carta_credito', models.CharField(max_length=19, null=True, validators=[F1.validators.valida_carta_credito])),
                ('cvv', models.CharField(max_length=3, null=True, validators=[F1.validators.valida_cvv])),
                ('scadenza_carta', models.DateField(null=True)),
                ('notifiche', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Utenti',
            },
        ),
        migrations.CreateModel(
            name='Ordine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('gestore_circuito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.gestore_circuito')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.utente')),
            ],
            options={
                'verbose_name_plural': 'Ordini',
            },
        ),
        migrations.CreateModel(
            name='Notifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('ordine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.ordine')),
            ],
            options={
                'verbose_name_plural': 'Notifiche',
            },
        ),
        migrations.CreateModel(
            name='Carrello',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('possedimento_carrello', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.utente')),
            ],
            options={
                'verbose_name_plural': 'Carrelli',
            },
        ),
        migrations.CreateModel(
            name='Biglietto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=50)),
                ('prezzo', models.FloatField(validators=[F1.validators.valida_non_negativi])),
                ('numero_posto', models.PositiveIntegerField()),
                ('carrello', models.ManyToManyField(blank=True, to='store.carrello')),
                ('gestore_circuito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.gestore_circuito')),
                ('ordine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='store.ordine')),
            ],
            options={
                'verbose_name_plural': 'Bliglietti',
            },
        ),
    ]
