# Generated by Django 4.2.1 on 2023-05-16 10:16

import F1.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biglietto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=50)),
                ('prezzo', models.FloatField(validators=[F1.validators.valida_non_negativi])),
                ('numero_posto', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Carrello',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Gestore_Circuito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sito_web', models.CharField(max_length=100)),
                ('indirizzo', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=25)),
                ('iban', models.CharField(max_length=34, validators=[F1.validators.valida_iban])),
                ('e_mail', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=100)),
                ('data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Ordine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cognome', models.CharField(max_length=50)),
                ('indirizzo', models.CharField(max_length=50)),
                ('paese', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=25)),
                ('e_mail', models.CharField(max_length=25, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('immagine_profilo', models.CharField(max_length=100)),
                ('premium', models.DateField(null=True)),
                ('carta_credito', models.CharField(max_length=19, null=True, validators=[F1.validators.valida_carta_credito])),
                ('cvv', models.CharField(max_length=3, null=True, validators=[F1.validators.valida_cvv])),
                ('scadenza_carta', models.DateField(null=True)),
            ],
        ),
    ]
