# Generated by Django 4.2.1 on 2023-05-31 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_remove_news_link_news_immagine_news_link_news'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestore_circuito',
            name='portale_f1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='media.portalef1'),
        ),
        migrations.AddField(
            model_name='utente',
            name='portale_f1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='media.portalef1'),
        ),
    ]
