# Generated by Django 4.2.1 on 2023-05-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biglietto',
            options={'verbose_name_plural': 'Bliglietti'},
        ),
        migrations.AlterModelOptions(
            name='carrello',
            options={'verbose_name_plural': 'Carrelli'},
        ),
        migrations.AlterModelOptions(
            name='gestore_circuito',
            options={'verbose_name_plural': 'Gestori circuiti'},
        ),
        migrations.AlterModelOptions(
            name='notifica',
            options={'verbose_name_plural': 'Notifiche'},
        ),
        migrations.AlterModelOptions(
            name='ordine',
            options={'verbose_name_plural': 'Ordini'},
        ),
        migrations.AlterModelOptions(
            name='utente',
            options={'verbose_name_plural': 'Utenti'},
        ),
        migrations.AlterField(
            model_name='utente',
            name='premium',
            field=models.DateField(blank=True, null=True),
        ),
    ]
