# Generated by Django 4.2.1 on 2023-06-23 17:22

import F1.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utente',
            name='carta_credito',
            field=models.CharField(default='', max_length=19, null=True, validators=[F1.validators.valida_carta_credito]),
        ),
        migrations.AlterField(
            model_name='utente',
            name='immagine_profilo',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='utente',
            name='indirizzo',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='utente',
            name='paese',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
