# Generated by Django 4.2.1 on 2023-06-24 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_utente_carta_credito_alter_utente_cvv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utente',
            name='immagine_profilo',
            field=models.CharField(blank=True, default='/static/users/default/default.jpg', max_length=100, null=True),
        ),
    ]
