# Generated by Django 4.2.1 on 2023-06-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_utente_data_nascita_alter_biglietto_data_evento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utente',
            name='sesso',
            field=models.CharField(blank=True, choices=[('M', 'Maschio'), ('F', 'Femmina')], max_length=10, null=True),
        ),
    ]
