# Generated by Django 4.2.2 on 2023-07-02 10:11

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_utente_sesso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utente',
            name='paese',
            field=django_countries.fields.CountryField(blank=True, default=None, max_length=2, null=True),
        ),
    ]
