# Generated by Django 4.2.2 on 2023-07-23 10:00

import F1.validators
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_utente_paese'),
    ]

    operations = [
        migrations.CreateModel(
            name='IstanzaBiglietto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_posto', models.PositiveIntegerField()),
                ('carrello', models.ManyToManyField(blank=True, to='store.carrello')),
                ('ordine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='store.ordine')),
            ],
            options={
                'verbose_name_plural': 'Bliglietti',
            },
        ),
        migrations.CreateModel(
            name='TipologiaBiglietto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=50)),
                ('data_evento', models.DateField(default=datetime.date.today)),
                ('prezzo', models.FloatField(validators=[F1.validators.valida_non_negativi])),
                ('totale_posti', models.PositiveIntegerField()),
                ('gestore_circuito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.gestore_circuito')),
            ],
            options={
                'verbose_name_plural': 'Tipologia Biglietti',
            },
        ),
        migrations.DeleteModel(
            name='Biglietto',
        ),
    ]
