# Generated by Django 4.2.2 on 2023-07-29 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_istanzabiglietto_tipologiabiglietto_delete_biglietto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='istanzabiglietto',
            options={'verbose_name_plural': 'Istanza Biglietti'},
        ),
    ]
