# Generated by Django 4.2.2 on 2023-07-29 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_istanzabiglietto_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='istanzabiglietto',
            name='tipologia_biglietto',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='store.tipologiabiglietto'),
        ),
    ]
