# Generated by Django 4.1.7 on 2023-08-05 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_istanzabiglietto_tipologia_biglietto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='istanzabiglietto',
            name='tipologia_biglietto',
        ),
        migrations.AddField(
            model_name='tipologiabiglietto',
            name='istanza_biglietto',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.istanzabiglietto'),
        ),
    ]
