# Generated by Django 4.1.7 on 2023-08-05 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_istanzabiglietto_tipologia_biglietto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipologiabiglietto',
            name='istanza_biglietto',
        ),
    ]
