# Generated by Django 4.2.2 on 2023-08-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_istanzabiglietto_tipologia_biglietto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='istanzabiglietto',
            name='carrello',
        ),
        migrations.AddField(
            model_name='carrello',
            name='istanze_biglietti',
            field=models.ManyToManyField(blank=True, to='store.istanzabiglietto'),
        ),
    ]
