# Generated by Django 4.2.2 on 2023-08-07 14:52

import F1.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_remove_istanzabiglietto_carrello_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipologiabiglietto',
            name='prezzo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[F1.validators.valida_non_negativi]),
        ),
    ]
