# Generated by Django 4.2.2 on 2023-08-08 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_tipologiabiglietto_prezzo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordine',
            name='gestore_circuito',
        ),
    ]
