# Generated by Django 4.2.2 on 2023-08-09 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_ordine_prezzo_alter_istanzabiglietto_ordine'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestore_circuito',
            name='email',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
