# Generated by Django 4.2.2 on 2023-08-09 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_gestore_circuito_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestore_circuito',
            name='email',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
