# Generated by Django 4.2.2 on 2023-08-09 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_alter_gestore_circuito_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipologiabiglietto',
            old_name='titolo',
            new_name='settore',
        ),
    ]
