# Generated by Django 4.2.2 on 2023-08-09 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_rename_titolo_tipologiabiglietto_settore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipologiabiglietto',
            name='totale_posti',
        ),
    ]
