# Generated by Django 4.2.4 on 2023-08-13 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_utente_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gestore_circuito',
            name='email',
        ),
    ]
