# Generated by Django 4.2.4 on 2023-08-14 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_remove_gestore_circuito_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utente',
            name='premium',
        ),
    ]
