# Generated by Django 4.2.1 on 2023-05-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=100)),
                ('video', models.CharField(max_length=100)),
                ('visualizzazioni', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('contenuto', models.CharField(max_length=500)),
                ('autore', models.CharField(max_length=50)),
                ('tags', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='PortaleF1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
