# Generated by Django 4.2.1 on 2023-06-02 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortaleF1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'PortaliF1',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('contenuto', models.CharField(max_length=500)),
                ('autore', models.CharField(max_length=50)),
                ('tags', models.CharField(max_length=250)),
                ('link_news', models.CharField(default='', max_length=250)),
                ('immagine', models.CharField(default='', max_length=250)),
                ('portale_f1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='media.portalef1')),
            ],
            options={
                'verbose_name_plural': 'News',
            },
        ),
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=100)),
                ('video', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('visualizzazioni', models.PositiveIntegerField(default=0)),
                ('preview', models.CharField(max_length=200)),
                ('portale_f1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='media.portalef1')),
            ],
        ),
    ]
