# Generated by Django 4.2.1 on 2023-05-31 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlight',
            name='portale_f1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='media.portalef1'),
        ),
        migrations.AddField(
            model_name='news',
            name='portale_f1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='media.portalef1'),
        ),
    ]
