# Generated by Django 4.2.1 on 2023-05-31 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_highlight_portale_f1_news_portale_f1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='link',
        ),
        migrations.AddField(
            model_name='news',
            name='immagine',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='news',
            name='link_news',
            field=models.CharField(default='', max_length=250),
        ),
    ]
