# Generated by Django 4.2.1 on 2023-05-15 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_highlight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portalef1',
            name='titolo',
        ),
    ]
