# Generated by Django 4.2.4 on 2023-08-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0011_circuito_data_evento'),
        ('media', '0003_remove_news_tags_news_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(default=None, null=True, to='info.scuderia'),
        ),
    ]
